name: Release Build

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      
      - name: Build Windows Application
        run: ./gradlew packageReleaseDistributionForCurrentOS
        
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: composeApp/build/compose/binaries/main-release/msi/*.msi
          
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      
      - name: Build MacOS Application
        run: ./gradlew packageReleaseDistributionForCurrentOS
        
      - name: Upload MacOS Artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-build
          path: composeApp/build/compose/binaries/main-release/dmg/*.dmg

  create-release:
    needs: [build-windows, build-macos]
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        
      - name: List Files
        run: |
          pwd
          ls -R
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            windows-build/*.msi
            macos-build/*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}